import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { Footer } from '~/components/Footer'
import { Main } from '~/components/Main'
import { x } from '@xstyled/emotion'

const Home: NextPage = () => {
  return (
    <x.div py={4}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main maxW={640} mx="auto" />
      <Footer mt={4} />
    </x.div>
  )
}

export default Home
